name: Test
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '34 18 * * *'
jobs:
  rake-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [head, 2.7, 2.6, 2.5, 2.4, 2.3, jruby, truffleruby]
        exclude:
          - os: windows-latest
            ruby: truffleruby
    runs-on: ${{ matrix.os }}
    # continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true    
    # - run: bundle install
    - run: bundle exec rake test
