name: Test
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '34 18 * * *'
jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
  rake-test:
    needs: ruby-versions
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - os: windows-latest
            ruby: jruby
          - os: windows-latest
            ruby: jruby-head
          - os: windows-latest
            ruby: truffleruby
          - os: windows-latest
            ruby: truffleruby-head
    runs-on: ${{ matrix.os }}
    # continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test
